# Generated by Django 5.2 on 2025-04-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosAPI', '0003_alter_customuser_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
