# Generated by Django 5.2 on 2025-04-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosAPI', '0003_perfilmedico_perfilpaciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='perfilpaciente',
            name='historial_médico',
            field=models.TextField(blank=True, default=' '),
        ),
    ]
