# Generated by Django 5.2 on 2025-04-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosAPI', '0004_remove_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('medico', models.ManyToManyField(related_name='especialidadMedico', to='UsuariosAPI.perfilmedico')),
            ],
        ),
        migrations.AddField(
            model_name='perfilmedico',
            name='especialidad',
            field=models.ManyToManyField(related_name='medicoEspecialidad', to='UsuariosAPI.especialidad'),
        ),
    ]
