# Generated by Django 5.2 on 2025-04-13 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosAPI', '0005_especialidad_perfilmedico_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidad',
            name='medico',
        ),
    ]
