# Generated by Django 5.2 on 2025-04-14 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosAPI', '0006_remove_especialidad_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('P', 'pendiente'), ('C', 'cancelada'), ('A', 'ausente'), ('R', 'realizada')], max_length=10)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsuariosAPI.perfilmedico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsuariosAPI.perfilpaciente')),
            ],
        ),
    ]
