# Generated by Django 5.2 on 2025-04-20 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosAPI', '0007_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='inicio',
            field=models.DateTimeField(default='2025-01-01 09:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HoraDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsuariosAPI.perfilmedico')),
            ],
            options={
                'ordering': ['inicio'],
                'unique_together': {('medico', 'inicio')},
            },
        ),
    ]
